build: false

init:
- ECHO %PYTHON%
environment:
  matrix:
  - PYTHON: C:/Python27-x64
  - PYTHON: C:/Python34-x64
  - PYTHON: C:/Python33-x64

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install pillow==2.9.0"
  
test_script:
- '%PYTHON%\python.exe setup.py test'

matrix:
  fast_finish: true